'use strict';
const db=window.aromartDb||window.supabaseClient;
const $=id=>document.getElementById(id),money=n=>'S/ '+Number(n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let clients=[],accounts=[],payments=[];
function notice(s){$('alert').textContent=s||''}
async function query(table,op){const r=await op(db.from(table));if(r.error)throw Error(r.error.message);return r.data}
async function load(){clients=await query('aromart_clients',q=>q.select('*').order('name'));accounts=await query('aromart_accounts',q=>q.select('*').order('created_at',{ascending:false}));payments=await query('aromart_payments',q=>q.select('*').order('created_at',{ascending:false}));render()}
function balance(a){return Math.max(0,Math.round((Number(a.total)-payments.filter(p=>p.account_id===a.id).reduce((s,p)=>s+Number(p.amount),0))*100)/100)}
function render(){const pending=accounts.reduce((s,a)=>s+balance(a),0);$('due').textContent=money(pending);$('reserved').textContent=accounts.filter(a=>a.kind==='separado'&&!a.delivered).length;$('count').textContent=clients.length;const sel=$('clientSelect'),current=sel.value;sel.replaceChildren(new Option('Selecciona un cliente',''),...clients.map(c=>new Option(c.name,c.id)));sel.value=clients.some(c=>c.id===current)?current:'';const term=$('search').value.toLowerCase();const filtered=accounts.filter(a=>{const c=clients.find(x=>x.id===a.client_id);return (a.product+' '+(c?.name||'')).toLowerCase().includes(term)});$('records').innerHTML=filtered.length?filtered.map(a=>{const c=clients.find(x=>x.id===a.client_id)||{},b=balance(a),paid=Number(a.total)-b,phone=(c.phone||'').replace(/\D/g,'');const msg=`Hola, ${c.name||'cliente'}. Te saludamos de AromArt Shop. ${b>0?`Te recordamos que tienes un saldo pendiente de ${money(b)} por ${a.product}.`:`Gracias por tu compra de ${a.product}.`} ¡Muchas gracias!`;const url=phone.length===9&&phone.startsWith('9')?'https://wa.me/51'+phone+'?text='+encodeURIComponent(msg):'';const hist=payments.filter(p=>p.account_id===a.id).map(p=>`${esc(p.created_at.slice(0,10))}: ${money(p.amount)} (${esc(p.method)})`).join(' · ');return `<article class="record"><div class="row"><div><b>${esc(c.name||'Cliente eliminado')}</b><p class="muted">${esc(a.product)} · ${esc(a.kind)} · ${esc(a.created_at.slice(0,10))}</p></div><span class="tag">${b===0?'Pagado':money(b)+' pendiente'}</span></div><div>Total: <b>${money(a.total)}</b> · Abonado: ${money(paid)}${a.due_date?' · Vence: '+esc(a.due_date):''}</div><div class="history">${hist||'Sin abonos'}</div><div class="actions"><button class="secondary" data-pay="${a.id}" ${b<=0?'disabled':''}>Registrar abono</button>${url?`<button class="green" data-wa="${esc(url)}">Enviar WhatsApp</button>`:''}${a.kind==='separado'&&!a.delivered?`<button class="secondary" data-deliver="${a.id}">Marcar entregado</button>`:''}</div></article>`}).join(''):'<p class="muted">Todavía no hay operaciones registradas.</p>'}
async function guarded(fn){try{notice('');await fn()}catch(e){notice('No se pudo completar: '+e.message)}}
$('clientForm').addEventListener('submit',e=>{e.preventDefault();guarded(async()=>{const f=e.target,v=Object.fromEntries(new FormData(f));if(v.phone&&!/^9\d{8}$/.test(v.phone))throw Error('WhatsApp debe tener 9 dígitos y empezar con 9');await query('aromart_clients',q=>q.insert({name:v.name.trim(),phone:v.phone||null}).select());f.reset();await load()})});
$('operationForm').addEventListener('submit',e=>{e.preventDefault();guarded(async()=>{const f=e.target,v=Object.fromEntries(new FormData(f)),total=Number(v.total),paid=Number(v.paid);if(!(total>0&&paid>=0&&paid<=total))throw Error('Revisa el total y el adelanto');if(v.kind==='venta'&&paid!==total)throw Error('Una venta pagada debe estar abonada por completo');const a=await query('aromart_accounts',q=>q.insert({client_id:v.client_id,kind:v.kind,product:v.product.trim(),total,due_date:v.due_date||null}).select().single());if(paid>0){try{await query('aromart_payments',q=>q.insert({account_id:a.id,amount:paid,method:v.method}).select())}catch(err){await query('aromart_accounts',q=>q.delete().eq('id',a.id));throw err}}f.reset();await load()})});
$('records').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.wa){window.open(b.dataset.wa,'_blank','noopener');return}if(b.dataset.pay){guarded(async()=>{const a=accounts.find(x=>x.id===b.dataset.pay),left=balance(a);const raw=prompt('¿Cuánto abonó el cliente? Saldo: '+money(left));if(raw===null)return;const amount=Number(raw.replace(',','.'));if(!Number.isFinite(amount)||amount<=0||amount>left)throw Error('El abono debe ser mayor a cero y no superar el saldo');const method=prompt('Método: Yape, Plin, Efectivo, Transferencia o Tarjeta','Yape');if(method===null)return;const valid=['Yape','Plin','Efectivo','Transferencia','Tarjeta'];const chosen=valid.find(x=>x.toLowerCase()===method.trim().toLowerCase());if(!chosen)throw Error('Método de pago no válido');await query('aromart_payments',q=>q.insert({account_id:a.id,amount,method:chosen}).select());await load()})}if(b.dataset.deliver){guarded(async()=>{if(!confirm('¿Confirmas que entregaste el producto?'))return;await query('aromart_accounts',q=>q.update({delivered:true}).eq('id',b.dataset.deliver).select());await load()})}});
$('search').addEventListener('input',render);
(async()=>{try{if(!db)throw Error('No se encontró la conexión a Supabase');const {data,error}=await db.auth.getSession();if(error)throw error;if(!data.session){location.replace('login.html');return}await load()}catch(e){notice('No se pudo cargar. Ejecuta primero el archivo SQL incluido en Supabase. Detalle: '+e.message)}})();
