function toggleMenu(btn){const links=btn.parentElement.querySelector('.links');if(!links)return;const open=links.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false');}
document.addEventListener('click',e=>{if(!e.target.closest('.nav'))document.querySelectorAll('.links.open').forEach(x=>x.classList.remove('open'))});
const PHONE='51932666874';
const INV_KEY='aromart_inventory_v2';
const CUSTOM_KEY='aromart_custom_products_v1', COUPON_KEY='aromart_coupon_v1', NOTICE_KEY='aromart_notice_v1';
const slug=n=>n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function shopItems(){const data=JSON.parse(localStorage.getItem(INV_KEY)||'{}'),custom=JSON.parse(localStorage.getItem(CUSTOM_KEY)||'[]');return [...STOCK,...UPCOMING,...custom].map(p=>{const x=data[slug(p.name)];if(!x)return {...p,status:p.upcoming?'proximamente':'disponible'};return {...p,price:x.price??p.price,status:x.status,qty:x.qty??0,upcoming:x.status==='proximamente'};});}
let cart=JSON.parse(localStorage.getItem('aromart_cart')||'[]');
const money=n=>n?`S/${n.toFixed(2).replace('.00','')}`:'Precio por anunciar';
function save(){localStorage.setItem('aromart_cart',JSON.stringify(cart));updateCount()}
function updateCount(){document.querySelectorAll('.cart-count').forEach(x=>x.textContent=cart.reduce((a,b)=>a+b.qty,0))}
function add(name,price,img){if(!price)return;const item=shopItems().find(i=>i.name===name);if(item&&(item.status!=='disponible'||(item.qty!=null&&item.qty<=0)))return;let x=cart.find(i=>i.name===name);if(x&&item?.qty!=null&&x.qty>=item.qty)return alert('No hay más unidades disponibles de este producto.');x?x.qty++:cart.push({name,price,img,qty:1});save();openCart()}
function change(name,d){let x=cart.find(i=>i.name===name);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.name!==name);save();renderCart()}
function openCart(){document.getElementById('cartModal').classList.add('open');renderCart()}function closeCart(){document.getElementById('cartModal').classList.remove('open')}
let appliedCoupon=null;
function validDateRange(x){const d=new Date().toISOString().slice(0,10);return (!x.start||d>=x.start)&&(!x.end||d<=x.end)}
function couponConfig(){try{return JSON.parse(localStorage.getItem(COUPON_KEY)||'{}')}catch(e){return {}}}
function applyCoupon(){const input=document.getElementById('couponInput'),msg=document.getElementById('couponMsg'),c=couponConfig(),code=(input?.value||'').trim().toUpperCase();if(c.active&&c.code&&code===String(c.code).toUpperCase()&&validDateRange(c)){appliedCoupon=c;msg.textContent=`✓ ${c.percent}% de descuento aplicado`;msg.className='coupon-msg ok'}else{appliedCoupon=null;msg.textContent='Código no válido o fuera de vigencia.';msg.className='coupon-msg bad'}renderCart()}
function renderCart(){let box=document.getElementById('cartItems');if(!box)return;box.innerHTML=cart.length?cart.map(i=>`<div class="cartrow"><div><b>${i.name}</b><div class="muted">${money(i.price)} c/u</div></div><div class="qty"><button onclick="change('${i.name.replaceAll("'","\\'")}',-1)">−</button><span>${i.qty}</span><button onclick="change('${i.name.replaceAll("'","\\'")}',1)">+</button></div></div>`).join(''):'<p class="muted">Tu carrito está vacío.</p>';let subtotal=cart.reduce((a,b)=>a+b.price*b.qty,0),discount=appliedCoupon?subtotal*(+appliedCoupon.percent||0)/100:0,total=subtotal-discount;document.getElementById('cartSubtotal').textContent=money(subtotal);document.getElementById('cartDiscount').textContent=discount?`− ${money(discount)}`:'S/0';document.getElementById('cartTotal').textContent=money(total)}
function checkout(){if(!cart.length)return;let subtotal=cart.reduce((a,b)=>a+b.price*b.qty,0),discount=appliedCoupon?subtotal*(+appliedCoupon.percent||0)/100:0,total=subtotal-discount;let msg='Hola AromArt Shop ✨ Quiero hacer este pedido:%0A%0A'+cart.map(i=>`• ${i.qty} x ${i.name} — ${money(i.price*i.qty)}`).join('%0A');if(discount)msg+=`%0A%0ACódigo: ${encodeURIComponent(appliedCoupon.code)} (${appliedCoupon.percent}% OFF)%0ADescuento: ${money(discount)}`;msg+=`%0A%0ATotal: ${money(total)}`;window.open(`https://wa.me/${PHONE}?text=${msg}`,'_blank')}
function notify(name){window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent('Hola AromArt Shop ✨ Quiero que me avisen cuando llegue: '+name)}`,'_blank')}
function card(i,up=false){let status=i.status||(up?'proximamente':'disponible'),isUp=status==='proximamente',sold=status==='agotado';let badge=isUp?'PRÓXIMAMENTE':sold?'AGOTADO':'EN STOCK';let action=isUp?`<button class="smallbtn ghost" onclick='notify(${JSON.stringify(i.name)})'>AVÍSAME</button>`:sold?`<button class="smallbtn ghost" disabled>AGOTADO</button>`:`<button class="smallbtn" onclick='add(${JSON.stringify(i.name)},${i.price||0},${JSON.stringify(i.img)})'>AGREGAR AL CARRITO</button>`;return `<article class="card"><span class="badge">${badge}</span><img class="pic" loading="lazy" src="${i.img?.startsWith('data:')?i.img:encodeURI(i.img)}" alt="${i.name}" onerror="this.onerror=null;this.src='assets/brand/logo.jpeg'"><div class="cardbody"><div class="tag">${i.cat.toUpperCase()}</div><h3>${i.name}</h3><div class="price">${money(i.price)}</div><p class="desc">${i.desc}</p>${action}</div></article>`}
function renderCatalog(){let box=document.getElementById('catalogGrid');if(!box)return;let q=(document.getElementById('search')?.value||'').toLowerCase(),cat=document.getElementById('category')?.value||'Todos';let a=shopItems().filter(i=>i.status!=='proximamente'&&(cat==='Todos'||i.cat===cat)&&i.name.toLowerCase().includes(q));box.innerHTML=a.map(i=>card(i)).join('');document.getElementById('count').textContent=a.length+' productos'}
function renderUpcoming(){let f=document.getElementById('fashionGrid'),o=document.getElementById('upGrid');if(!o)return;let upcoming=shopItems().filter(i=>i.status==='proximamente'),fashion=upcoming.filter(i=>i.name.includes('Fashion Show'));if(f)f.innerHTML=fashion.map(i=>card(i,true)).join('');o.innerHTML=upcoming.filter(i=>!i.name.includes('Fashion Show')).map(i=>card(i,true)).join('')}
function renderNotice(){let n={};try{n=JSON.parse(localStorage.getItem(NOTICE_KEY)||'{}')}catch(e){};if(!n.active||!validDateRange(n)||(!n.title&&!n.text))return;const el=document.createElement('div');el.className='special-notice';el.innerHTML=`<b>${n.title||'AromArt Shop'}</b>${n.text?`<span>${n.text}</span>`:''}<button aria-label="Cerrar" onclick="this.parentElement.remove()">×</button>`;document.body.prepend(el)}
document.addEventListener('DOMContentLoaded',()=>{renderNotice();updateCount();renderCatalog();renderUpcoming();let feat=document.getElementById('featured');if(feat)feat.innerHTML=shopItems().filter(i=>i.status==='disponible').slice(0,8).map(i=>card(i)).join('');document.getElementById('search')?.addEventListener('input',renderCatalog);document.getElementById('category')?.addEventListener('change',renderCatalog);let r=document.querySelector('.reveal');if(r){setTimeout(()=>r.classList.add('hide'),3500);r.onclick=()=>r.classList.add('hide')}})
