const PHONE='51932666874';
const INV_KEY='aromart_inventory_v2';
const slug=n=>n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function shopItems(){const data=JSON.parse(localStorage.getItem(INV_KEY)||'{}');return [...STOCK,...UPCOMING].map(p=>{const x=data[slug(p.name)];if(!x)return {...p,status:p.upcoming?'proximamente':'disponible'};return {...p,price:x.price??p.price,status:x.status,qty:x.qty??0,upcoming:x.status==='proximamente'};});}
let cart=JSON.parse(localStorage.getItem('aromart_cart')||'[]');
const money=n=>n?`S/${n.toFixed(2).replace('.00','')}`:'Precio por anunciar';
function save(){localStorage.setItem('aromart_cart',JSON.stringify(cart));updateCount()}
function updateCount(){document.querySelectorAll('.cart-count').forEach(x=>x.textContent=cart.reduce((a,b)=>a+b.qty,0))}
function add(name,price,img){if(!price)return;let x=cart.find(i=>i.name===name);x?x.qty++:cart.push({name,price,img,qty:1});save();openCart()}
function change(name,d){let x=cart.find(i=>i.name===name);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.name!==name);save();renderCart()}
function openCart(){document.getElementById('cartModal').classList.add('open');renderCart()}function closeCart(){document.getElementById('cartModal').classList.remove('open')}
function renderCart(){let box=document.getElementById('cartItems');if(!box)return;box.innerHTML=cart.length?cart.map(i=>`<div class="cartrow"><div><b>${i.name}</b><div class="muted">${money(i.price)} c/u</div></div><div class="qty"><button onclick="change('${i.name.replaceAll("'","\\'")}',-1)">−</button><span>${i.qty}</span><button onclick="change('${i.name.replaceAll("'","\\'")}',1)">+</button></div></div>`).join(''):'<p class="muted">Tu carrito está vacío.</p>';let t=cart.reduce((a,b)=>a+b.price*b.qty,0);document.getElementById('cartTotal').textContent=money(t)}
function checkout(){if(!cart.length)return;let t=cart.reduce((a,b)=>a+b.price*b.qty,0);let msg='Hola AromArt Shop ✨ Quiero hacer este pedido:%0A%0A'+cart.map(i=>`• ${i.qty} x ${i.name} — ${money(i.price*i.qty)}`).join('%0A')+`%0A%0ATotal: ${money(t)}`;window.open(`https://wa.me/${PHONE}?text=${msg}`,'_blank')}
function notify(name){window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent('Hola AromArt Shop ✨ Quiero que me avisen cuando llegue: '+name)}`,'_blank')}
function card(i,up=false){let status=i.status||(up?'proximamente':'disponible'),isUp=status==='proximamente',sold=status==='agotado';let badge=isUp?'PRÓXIMAMENTE':sold?'AGOTADO':'EN STOCK';let action=isUp?`<button class="smallbtn ghost" onclick='notify(${JSON.stringify(i.name)})'>AVÍSAME</button>`:sold?`<button class="smallbtn ghost" disabled>AGOTADO</button>`:`<button class="smallbtn" onclick='add(${JSON.stringify(i.name)},${i.price||0},${JSON.stringify(i.img)})'>AGREGAR AL CARRITO</button>`;return `<article class="card"><span class="badge">${badge}</span><img class="pic" loading="lazy" src="${encodeURI(i.img)}" alt="${i.name}"><div class="cardbody"><div class="tag">${i.cat.toUpperCase()}</div><h3>${i.name}</h3><div class="price">${money(i.price)}</div><p class="desc">${i.desc}</p>${action}</div></article>`}
function renderCatalog(){let box=document.getElementById('catalogGrid');if(!box)return;let q=(document.getElementById('search')?.value||'').toLowerCase(),cat=document.getElementById('category')?.value||'Todos';let a=shopItems().filter(i=>i.status!=='proximamente'&&(cat==='Todos'||i.cat===cat)&&i.name.toLowerCase().includes(q));box.innerHTML=a.map(i=>card(i)).join('');document.getElementById('count').textContent=a.length+' productos'}
function renderUpcoming(){let f=document.getElementById('fashionGrid'),o=document.getElementById('upGrid');if(!o)return;let upcoming=shopItems().filter(i=>i.status==='proximamente'),fashion=upcoming.filter(i=>i.name.includes('Fashion Show'));if(f)f.innerHTML=fashion.map(i=>card(i,true)).join('');o.innerHTML=upcoming.filter(i=>!i.name.includes('Fashion Show')).map(i=>card(i,true)).join('')}
document.addEventListener('DOMContentLoaded',()=>{updateCount();renderCatalog();renderUpcoming();let feat=document.getElementById('featured');if(feat)feat.innerHTML=shopItems().filter(i=>i.status==='disponible').slice(0,8).map(i=>card(i)).join('');document.getElementById('search')?.addEventListener('input',renderCatalog);document.getElementById('category')?.addEventListener('change',renderCatalog);let r=document.querySelector('.reveal');if(r){setTimeout(()=>r.classList.add('hide'),3500);r.onclick=()=>r.classList.add('hide')}})
